"""
checklist/output.py — Render compliance checklists as HTML or Markdown.

Provides clean, actionable output formats suitable for fintech founders
who need to review and act on their compliance requirements.
"""

from .generator import ComplianceChecklist, ChecklistItem


# ─── Markdown Output ─────────────────────────────────────────────────────────


def to_markdown(checklist: ComplianceChecklist) -> str:
    """Render a compliance checklist as Markdown."""
    lines = []
    s = checklist.summary

    lines.append(f"# Compliance Checklist: {checklist.display_name}")
    lines.append(f"")
    lines.append(f"**Generated:** {checklist.generated_at}")
    lines.append(f"**Jurisdiction:** {checklist.jurisdiction}")
    lines.append(f"")
    lines.append(f"## Summary")
    lines.append(f"")
    lines.append(f"- **{s['total_items']}** total requirements")
    lines.append(f"- **{s['critical']}** critical (must-do immediately)")
    lines.append(f"- **{s['high_priority']}** high priority (do within 90 days)")
    lines.append(f"- Categories: {', '.join(s['categories'])}")
    lines.append(f"")

    # Group by category
    categorized = checklist.categorized_items()
    category_labels = {
        "aml": "🔒 AML / BSA Compliance",
        "consumer_protection": "📋 Consumer Protection",
        "privacy": "🔐 Privacy & Data Protection",
        "licensing": "📄 Licensing & Registration",
        "securities": "📈 Securities Compliance",
        "cybersecurity": "🛡️ Cybersecurity",
        "banking": "🏦 Banking / Partnership",
        "other": "📌 Other Requirements",
    }

    for category_slug, items in categorized.items():
        label = category_labels.get(category_slug, category_slug.title())
        lines.append(f"## {label}")
        lines.append(f"")

        for item in items:
            emoji = "🔴" if item.priority <= 2 else "🟡" if item.priority <= 4 else "🟢"
            effort_badge = {
                "low": "✅ Low effort",
                "medium": "🔧 Medium effort",
                "high": "🏗️ High effort",
            }.get(item.estimated_effort, item.estimated_effort)

            lines.append(f"### {emoji} {item.title}")
            if item.section:
                lines.append(f"**Section:** `{item.section}`")
            lines.append(f"**Priority:** {item.priority}/10 | **Effort:** {effort_badge}")
            if item.description:
                lines.append(f"")
                lines.append(f"{item.description}")
            lines.append(f"")
            lines.append(f"**Action items:**")
            for action in item.action_items:
                lines.append(f"- [ ] {action}")
            lines.append(f"")
            if item.resources:
                lines.append(f"**Resources:**")
                for res in item.resources:
                    lines.append(f"- [{res['title']}]({res['url']})")
            lines.append(f"")

    lines.append("---")
    lines.append(f"*This checklist was generated by complyAI and is for informational purposes only. It does not constitute legal advice. Consult with a qualified attorney for your specific situation.*")

    return "\n".join(lines)


# ─── HTML Output ─────────────────────────────────────────────────────────────


HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Compliance Checklist — {display_name} | complyAI</title>
<style>
  *, *::before, *::after {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; color: #1a1a2e; background: #f8f9fa; line-height: 1.6; }}
  .container {{ max-width: 900px; margin: 0 auto; padding: 2rem 1.5rem; }}

  header {{ text-align: center; margin-bottom: 2rem; }}
  h1 {{ font-size: 2rem; color: #16213e; }}
  .meta {{ color: #666; font-size: 0.9rem; margin-top: 0.5rem; }}

  .summary {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 1rem; margin-bottom: 2rem; }}
  .stat {{ background: white; border-radius: 8px; padding: 1.25rem; text-align: center; box-shadow: 0 1px 3px rgba(0,0,0,0.08); }}
  .stat-value {{ font-size: 2rem; font-weight: 700; }}
  .stat-label {{ font-size: 0.85rem; color: #666; margin-top: 0.25rem; }}
  .stat.critical .stat-value {{ color: #dc2626; }}
  .stat.high .stat-value {{ color: #ea580c; }}
  .stat.total .stat-value {{ color: #16213e; }}

  .category {{ margin-bottom: 2.5rem; }}
  .category h2 {{ font-size: 1.3rem; color: #16213e; border-bottom: 2px solid #e5e7eb; padding-bottom: 0.5rem; margin-bottom: 1rem; }}

  .item {{ background: white; border-radius: 8px; padding: 1.25rem; margin-bottom: 1rem; box-shadow: 0 1px 3px rgba(0,0,0,0.08); border-left: 4px solid #22c55e; }}
  .item.priority-critical {{ border-left-color: #dc2626; }}
  .item.priority-high {{ border-left-color: #ea580c; }}
  .item.priority-medium {{ border-left-color: #eab308; }}
  .item h3 {{ font-size: 1.05rem; margin-bottom: 0.5rem; }}
  .item .section {{ font-family: monospace; background: #f3f4f6; padding: 0.15rem 0.4rem; border-radius: 3px; font-size: 0.85rem; }}
  .item .tags {{ display: flex; gap: 0.5rem; flex-wrap: wrap; margin: 0.5rem 0; }}
  .item .tag {{ font-size: 0.8rem; padding: 0.15rem 0.5rem; border-radius: 999px; background: #f3f4f6; color: #666; }}
  .item .tag.critical {{ background: #fef2f2; color: #dc2626; }}
  .item .tag.high {{ background: #fff7ed; color: #ea580c; }}
  .item .description {{ color: #374151; margin: 0.5rem 0; }}
  .item .actions {{ margin-top: 0.75rem; }}
  .item .actions li {{ list-style: none; padding: 0.25rem 0; font-size: 0.9rem; }}
  .item .actions li::before {{ content: "☐ "; }}
  .item .resources {{ margin-top: 0.75rem; font-size: 0.85rem; }}
  .item .resources a {{ color: #2563eb; text-decoration: none; }}
  .item .resources a:hover {{ text-decoration: underline; }}

  footer {{ text-align: center; color: #9ca3af; font-size: 0.85rem; margin-top: 3rem; padding-top: 1.5rem; border-top: 1px solid #e5e7eb; }}

  @media print {{
    body {{ background: white; }}
    .item {{ break-inside: avoid; box-shadow: none; border: 1px solid #e5e7eb; }}
    .summary {{ break-inside: avoid; }}
  }}
</style>
</head>
<body>
<div class="container">
  <header>
    <h1>📋 Compliance Checklist: {display_name}</h1>
    <p class="meta">Generated {generated_at} &middot; Jurisdiction: {jurisdiction}</p>
  </header>

  <div class="summary">
    <div class="stat total">
      <div class="stat-value">{total}</div>
      <div class="stat-label">Total Requirements</div>
    </div>
    <div class="stat critical">
      <div class="stat-value">{critical}</div>
      <div class="stat-label">Critical (Act Now)</div>
    </div>
    <div class="stat high">
      <div class="stat-value">{high}</div>
      <div class="stat-label">High Priority (90 Days)</div>
    </div>
  </div>

  {categories_html}

  <footer>
    <p>This checklist was generated by <strong>complyAI</strong> and is for informational purposes only.</p>
    <p>It does not constitute legal advice. Consult with a qualified attorney for your specific situation.</p>
  </footer>
</div>
</body>
</html>"""


def to_html(checklist: ComplianceChecklist) -> str:
    """Render a compliance checklist as a standalone HTML page."""
    s = checklist.summary
    categorized = checklist.categorized_items()

    category_labels = {
        "aml": "🔒 AML / BSA Compliance",
        "consumer_protection": "📋 Consumer Protection",
        "privacy": "🔐 Privacy & Data Protection",
        "licensing": "📄 Licensing & Registration",
        "securities": "📈 Securities Compliance",
        "cybersecurity": "🛡️ Cybersecurity",
        "banking": "🏦 Banking / Partnership",
        "other": "📌 Other Requirements",
    }

    categories_html_parts = []

    for cat_slug, items in categorized.items():
        label = category_labels.get(cat_slug, cat_slug.title())
        items_html = []
        for item in items:
            priority_class = "priority-critical" if item.priority <= 2 else "priority-high" if item.priority <= 4 else "priority-medium"
            effort_badge = {"low": "✅ Low", "medium": "🔧 Medium", "high": "🏗️ High"}.get(item.estimated_effort, item.estimated_effort)
            section_html = f' <span class="section">{item.section}</span>' if item.section else ""
            description_html = f'<p class="description">{item.description}</p>' if item.description else ""

            actions_html = ""
            if item.action_items:
                items_list = "\n".join(f"<li>{a.replace('🚨 ', '').replace('🚨', '')}</li>" for a in item.action_items)
                actions_html = f'<ol class="actions">{items_list}</ol>'

            resources_html = ""
            if item.resources:
                res_links = "\n".join(f'<li><a href="{r["url"]}" target="_blank">{r["title"]}</a></li>' for r in item.resources)
                resources_html = f'<div class="resources"><strong>Resources:</strong><ul>{res_links}</ul></div>'

            items_html.append(f"""\
    <div class="item {priority_class}">
      <h3>{item.title}{section_html}</h3>
      <div class="tags">
        <span class="tag">Priority: {item.priority}/10</span>
        <span class="tag">{effort_badge}</span>
      </div>
      {description_html}
      {actions_html}
      {resources_html}
    </div>""")

        categories_html_parts.append(f"""\
  <div class="category">
    <h2>{label}</h2>
    {''.join(items_html)}
  </div>""")

    return HTML_TEMPLATE.format(
        display_name=checklist.display_name,
        generated_at=checklist.generated_at,
        jurisdiction=checklist.jurisdiction,
        total=s["total_items"],
        critical=s["critical"],
        high=s["high_priority"],
        categories_html="\n".join(categories_html_parts),
    )


if __name__ == "__main__":
    from .generator import generate_checklist

    # Generate and output a sample
    checklist = generate_checklist("payments")
    if checklist:
        md = to_markdown(checklist)
        print(md[:2000])
        print("\n\n---\n\n")
        print("[HTML output omitted — use generate_checklist().to_html()]")
